# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocktailChoose' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocktailChoose
  pod 'Kingfisher', '~> 6.3.0'

  target 'CocktailChooseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocktailChooseUITests' do
    # Pods for testing
  end

end
