# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'cocoapods', '1.10.0'
gem 'slather', '2.7.0'
gem 'danger'
