# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foody (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foody (iOS)
  pod 'Moya', '~> 14.0'
 
  pod 'ImagePicker'
  pod 'SDWebImageSwiftUI'
  pod 'ToastUI'
  pod 'SwifterSwift', '~> 5.2.0'
  pod 'SwiftyUserDefaults', '~> 5.0'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'AlamofireNetworkActivityIndicator', '~> 3.1'
  # pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  pod 'PhoneNumberKit', '~> 3.3'
  pod 'Introspect'
  pod 'SwiftyGif'
  pod 'Charts'
  
  pod 'WaterfallGrid', '~> 1.0.0'
  
  # Recommended: Add the Firebase pod
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Storage'

  
  # Combine
  pod 'CombineExt'

end

target 'Foody (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foody (macOS)

end
